services:
  - type: web
    name: directus
    runtime: docker
    plan: free
    dockerfilePath: ./Dockerfile

    # Wichtig: Directus soll seine öffentliche URL kennen.
    # Auf Render kannst du direkt die Service-URL injizieren:
    envVars:
      - key: DB_CLIENT
        value: pg
      - key: DB_HOST
        fromDatabase:
          name: directus-db
          property: host
      - key: DB_PORT
        fromDatabase:
          name: directus-db
          property: port
      - key: DB_DATABASE
        fromDatabase:
          name: directus-db
          property: database
      - key: DB_USER
        fromDatabase:
          name: directus-db
          property: user
      - key: DB_PASSWORD
        fromDatabase:
          name: directus-db
          property: password

      - key: KEY
        generateValue: true
      - key: SECRET
        generateValue: true

      - key: ADMIN_EMAIL
        value: admin@example.com
      - key: ADMIN_PASSWORD
        value: directus123

      # Hier bitte "url" statt "host", damit https://... reinkommt.
      - key: PUBLIC_URL
        fromService:
          type: web
          name: directus
          property: url

      - key: CORS_ENABLED
        value: "true"
      - key: CORS_ORIGIN
        value: https://directus-blueprint.vercel.app,http://localhost:3000

    # Optional aber sehr empfehlenswert (Uploads persistent):
    disks:
      - name: uploads
        mountPath: /directus/uploads
        sizeGB: 1

databases:
  - name: directus-db
    databaseName: directus
    user: directus
    plan: free
